name: featureforest
channels:
  - conda-forge
dependencies:
  - python =3.10
  - pyqt =5.15
  - qtpy
  - magicgui
  - scikit-learn
  - scikit-image
  - scipy
  - napari
  - h5py
  - pytorch =2.3.1
  - torchvision =0.18.1
  - sam-2
  - pooch
  - timm ==1.0.9
  - numpy ==1.24.4    # timm drops deprecation warnings with newer versions
  - matplotlib
  - pynrrd
  - iopath >=0.1.10
  - pip
  - pip:
    - opencv-python
    - git+https://github.com/facebookresearch/segment-anything.git
    - git+https://github.com/juglab/featureforest.git
