site_name: Feature Forest Documents
site_url: https://mydomain.org/mysite
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.footer
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
  # logo: assets/logo.png
  # favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Parkinsans
    code: Fira Code
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

extra:
  version:
      provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/juglab/featureforest

repo_url: https://github.com/juglab/featureforest
repo_name: juglab/featureforest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences