site_name: Feature Forest Documentation
site_url: https://juglab.github.io/featureforest
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  # logo: assets/logo.png
  # favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Parkinsans
    code: Fira Code
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - content.code.copy

nav:
  - Welcome: index.md
  - Installation: install.md
  - How to use the plugin: howto.md
  - Feature Extractor Widget: feature_extractor.md
  - Segmentation Widget: segmentation.md
  - Adapting New Models: model_adapter.md

extra:
  version:
      provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/juglab/featureforest

repo_url: https://github.com/juglab/featureforest
repo_name: juglab/featureforest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.caption
  - def_list
  - sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true