name: Test and Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3.1.0
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ff
          python-version: ${{ matrix.python-version }}
          channels: pytorch, conda-forge, defaults
          channel-priority: true
          use-only-tar-bz2: true
          environment-file: env_cpu.yml

      - name: Conda info
        run: conda info

      - name: Jupyter
        run: conda install jupyterlab
